import type { Trail, QuizQuestion } from "./schemas"

export const mockQuizQuestions: QuizQuestion[] = [
  {
    id: "q1",
    question: "Qual o prazo medio para pagar a fatura do cartao sem juros?",
    preContent: "Dica de Ouro: O cartao de credito possui um dia de fechamento e um dia de vencimento.",
    options: ["5 dias", "10 dias", "30 dias", "40 dias"],
    correctIndex: 2,
  },
  {
    id: "q2",
    question: "O que acontece se voce pagar apenas o minimo da fatura?",
    preContent: "Pagar o minimo e uma das armadilhas mais caras do Brasil.",
    options: ["Nada, esta tudo certo", "Voce entra no rotativo e paga juros altos", "Seu limite aumenta", "Voce ganha cashback"],
    correctIndex: 1,
  },
  {
    id: "q3",
    question: "Qual a melhor estrategia para usar o cartao de credito?",
    preContent: "O cartao deve ser uma ferramenta de fluxo de caixa, nao um complemento de renda.",
    options: ["Pagar sempre o minimo", "Parcelar tudo em 12x", "Pagar a fatura total todo mes", "Usar o limite todo"],
    correctIndex: 2,
  },
]

export const mockTrails: Trail[] = [
  {
    id: "trail-1",
    title: "Fundamentos Financeiros",
    description: "Aprenda o básico sobre dinheiro e como ele funciona no mundo real.",
    icon: "Wallet",
    color: "from-emerald-500 to-teal-600",
    isPro: false,
    totalLessons: 8,
    completedLessons: 0,
    lessons: [
      { id: "t1-1", title: "O que é dinheiro?", description: "A base de tudo", content: "Dinheiro é uma ferramenta criada para facilitar trocas.", activityContent: "Identifique as três funções do dinheiro.", duration: "3 min", xpReward: 50, isCompleted: false, isLocked: false, isPro: false, icon: "Coins", category: "Básico", tips: ["O cartão de crédito possui fechamento e vencimento.", "Sempre pague o total da fatura."] },
      { id: "t1-2", title: "Mentalidade de Riqueza", description: "Como os ricos pensam", content: "Riqueza não é o quanto você ganha, mas o quanto você mantém.", activityContent: "Diferencie um Ativo de um Passivo.", duration: "4 min", xpReward: 60, isCompleted: false, isLocked: true, isPro: false, icon: "Sparkles", category: "Mindset", tips: ["Um carro de luxo para uso próprio é um passivo.", "Pague-se primeiro."] },
      { id: "t1-3", title: "Inflação Simplificada", description: "O inimigo invisível", content: "Inflação é o aumento generalizado dos preços.", activityContent: "Calcule o poder de compra perdido com 10% ao ano.", duration: "5 min", xpReward: 70, isCompleted: false, isLocked: true, isPro: false, icon: "TrendingUp", category: "Economia", tips: ["Inflação alta favorece devedores.", "O IPCA é o principal índice."] },
      { id: "t1-4", title: "Juros Compostos", description: "A oitava maravilha do mundo", content: "Juros sobre juros. No longo prazo, o tempo é mais importante.", activityContent: "Projete o crescimento de um capital por 10 anos.", duration: "5 min", xpReward: 80, isCompleted: false, isLocked: true, isPro: false, icon: "Zap", category: "Investimentos", tips: ["A regra dos 72 ajuda a estimar em quanto tempo seu dinheiro dobra.", "Começar cedo é mais importante."] },
      { id: "t1-5", title: "Segurança de Dados", description: "Proteja seu patrimônio", content: "No mundo digital, senhas fortes e 2FA são essenciais.", activityContent: "Identifique ataques de Phishing comuns.", duration: "4 min", xpReward: 50, isCompleted: false, isLocked: true, isPro: false, icon: "Shield", category: "Segurança", tips: ["Use gerenciadores de senhas.", "Ative verificação em duas etapas."] },
      { id: "t1-6", title: "A Regra 50/30/20", description: "Organize seu orçamento", content: "50% necessidades, 30% desejos, 20% futuro.", activityContent: "Aloque despesas em cada categoria.", duration: "5 min", xpReward: 65, isCompleted: false, isLocked: true, isPro: false, icon: "BarChart3", category: "Orçamento", tips: ["Se suas necessidades passam de 50%, reduza custos fixos.", "Faça os 20% crescerem."] },
      { id: "t1-7", title: "Dívidas vs Investimentos", description: "O que priorizar?", content: "Dívidas de juros altos devem ser pagas antes de investir.", activityContent: "Determine se vale investir 10% ou pagar dívida de 12% ao mês.", duration: "6 min", xpReward: 75, isCompleted: false, isLocked: true, isPro: false, icon: "ArrowUpRight", category: "Dívidas", tips: ["Juros de dívidas quase sempre superam investimentos.", "Negocie dívidas antes de investir."] },
      { id: "t1-8", title: "Sua Primeira Reserva", description: "O fim do estresse financeiro", content: "Comece com R$ 1.000. Depois, busque 6 meses de custo de vida.", activityContent: "Calcule sua reserva de emergência.", duration: "7 min", xpReward: 100, isCompleted: false, isLocked: true, isPro: false, icon: "PiggyBank", category: "Reserva", tips: ["A reserva deve ter liquidez diária.", "Não use para consumo."] },
    ],
  },
  {
    id: "trail-2",
    title: "Crédito Inteligente",
    description: "Domine o cartão de crédito e as ferramentas bancárias.",
    icon: "CreditCard",
    color: "from-purple-500 to-indigo-600",
    isPro: false,
    totalLessons: 6,
    completedLessons: 0,
    lessons: [
      { id: "t2-1", title: "Ouro no Cartão", description: "Como funciona o ciclo", content: "O cartão é um empréstimo de curto prazo.", activityContent: "Encontre a melhor data de compra.", duration: "4 min", xpReward: 55, isCompleted: false, isLocked: false, isPro: false, icon: "CreditCard", category: "Cartão", tips: ["O fechamento ocorre 10 dias antes do vencimento.", "Centralize gastos no cartão."] },
      { id: "t2-2", title: "Limite e Score", description: "Seu valor para o banco", content: "Score é sua reputação financeira.", activityContent: "Identifique comportamentos que aumentam seu Score.", duration: "5 min", xpReward: 60, isCompleted: false, isLocked: true, isPro: false, icon: "TrendingUp", category: "Crédito", tips: ["Manter o Cadastro Positivo ativo ajuda.", "Evite pedir crédito em vários bancos."] },
      { id: "t2-3", title: "Juros do Rotativo", description: "A maior armadilha", content: "Nunca pague o mínimo.", activityContent: "Simule crescimento de uma fatura de R$ 1.000 por 3 meses.", duration: "5 min", xpReward: 70, isCompleted: false, isLocked: true, isPro: false, icon: "Percent", category: "Alerta", tips: ["Busque parcelamento, que tem juros menores.", "O rotativo é ativado automaticamente."] },
      { id: "t2-4", title: "Milhas e Pontos", description: "Dinheiro de volta", content: "Seus gastos podem virar passagens aéreas.", activityContent: "Calcule a conversão de gastos para pontos.", duration: "4 min", xpReward: 50, isCompleted: false, isLocked: true, isPro: false, icon: "Sparkles", category: "Benefícios", tips: ["Fique atento às promoções de transferência bonificada.", "Não pague anuidade cara por pontos."] },
      { id: "t2-5", title: "Anuidade e Taxas", description: "Negocie como um mestre", content: "Muitos bancos cobram taxas que podem ser isentas.", activityContent: "Escolha os melhores argumentos para pedir isenção.", duration: "4 min", xpReward: 45, isCompleted: false, isLocked: true, isPro: false, icon: "MessageCircle", category: "Economia", tips: ["Bancos digitais têm cartões sem anuidade.", "Se negarem, troque para cartão gratuito."] },
      { id: "t2-6", title: "Empréstimos Bancários", description: "Quando valem a pena?", content: "Consignado e financiamento imobiliário são ferramentas.", activityContent: "Ordene as modalidades de crédito da mais barata.", duration: "6 min", xpReward: 80, isCompleted: false, isLocked: true, isPro: false, icon: "DollarSign", category: "Crédito", tips: ["O crédito consignado é barato.", "Evite o cheque especial."] },
    ],
  },
  {
    id: "trail-3",
    title: "Domínio da Renda Fixa",
    description: "Invista com segurança e ganhe do CDI.",
    icon: "Building2",
    color: "from-blue-500 to-cyan-600",
    isPro: false,
    totalLessons: 6,
    completedLessons: 0,
    lessons: [
      { id: "t3-1", title: "O que é Renda Fixa?", description: "Emprestando para o banco", content: "Investir em renda fixa é como emprestar seu dinheiro.", activityContent: "Identifique quem é o emissor.", duration: "5 min", xpReward: 60, isCompleted: false, isLocked: false, isPro: false, icon: "Building2", category: "Conceito", tips: ["Renda fixa não significa lucro fixo.", "O IOF incide nos primeiros 30 dias."] },
      { id: "t3-2", title: "Selic e CDI", description: "As taxas mestras", content: "A Selic é a taxa do governo. O CDI é a taxa entre bancos.", activityContent: "Calcule o rendimento de 100% do CDI.", duration: "5 min", xpReward: 65, isCompleted: false, isLocked: true, isPro: false, icon: "Percent", category: "Taxas", tips: ["CDI costuma ser 0,10% menor que a Selic.", "Quando Selic sobe, renda fixa fica mais atrativa."] },
      { id: "t3-3", title: "Tesouro Direto", description: "Mais seguro do país", content: "SELIC (liquidez), IPCA (inflação) e Prefixado (garantia).", activityContent: "Escolha o melhor título para uma viagem em 5 anos.", duration: "6 min", xpReward: 75, isCompleted: false, isLocked: true, isPro: false, icon: "Map", category: "Governo" },
      { id: "t3-4", title: "CDB, LCI e LCA", description: "Bancos e Setores", content: "LCI e LCA são isentos de IR.", activityContent: "Compare CDB de 115% vs LCI de 95% do CDI.", duration: "6 min", xpReward: 70, isCompleted: false, isLocked: true, isPro: false, icon: "Coins", category: "Bancos" },
      { id: "t3-5", title: "O Poder do FGC", description: "Sua garantia real", content: "O FGC protege até R$ 250 mil por CPF.", activityContent: "Determine o risco de investir em banco pequeno.", duration: "4 min", xpReward: 50, isCompleted: false, isLocked: true, isPro: false, icon: "Shield", category: "Segurança" },
      { id: "t3-6", title: "Montando seu Portfólio", description: "Estratégia completa", content: "Diversificar em renda fixa também é importante.", activityContent: "Crie uma carteira equilibrando liquidez e rentabilidade.", duration: "7 min", xpReward: 90, isCompleted: false, isLocked: true, isPro: false, icon: "Wallet", category: "Estratégia" },
    ],
  },
  {
    id: "trail-4",
    title: "Ações e Bolsa",
    description: "Aprenda a investir em empresas e tornar-se sócio.",
    icon: "BarChart3",
    color: "from-amber-400 to-yellow-600",
    isPro: true,
    totalLessons: 6,
    completedLessons: 0,
    lessons: [
      { id: "t4-1", title: "O que são Ações?", description: "Tornando-se sócio", content: "Ações representam a menor fração do capital.", activityContent: "Diferencie ações ON de PN.", duration: "5 min", xpReward: 70, isCompleted: false, isLocked: true, isPro: true, icon: "Building2", category: "Bolsa", tips: ["Investir em ações é focar no longo prazo.", "Você ganha com valorização e dividendos."] },
      { id: "t4-2", title: "Análise Fundamentalista", description: "Saúde das empresas", content: "Olhar lucro, dívida e governança.", activityContent: "Analise o P/L de uma empresa fictícia.", duration: "7 min", xpReward: 100, isCompleted: false, isLocked: true, isPro: true, icon: "TrendingUp", category: "Análise" },
      { id: "t4-3", title: "Dividendos e JCP", description: "Renda passiva", content: "Empresas distribuem parte dos lucros.", duration: "6 min", xpReward: 80, isCompleted: false, isLocked: true, isPro: true, icon: "DollarSign", category: "Renda" },
      { id: "t4-4", title: "Dividend Yield", description: "Quanto a empresa paga?", content: "DY é a relação entre dividendo e preço.", duration: "5 min", xpReward: 75, isCompleted: false, isLocked: true, isPro: true, icon: "Percent", category: "Métricas" },
      { id: "t4-5", title: "Diversificação Real", description: "Não coloque todos os ovos numa cesta", content: "Distribuir entre setores reduz riscos.", duration: "6 min", xpReward: 85, isCompleted: false, isLocked: true, isPro: true, icon: "BarChart3", category: "Estratégia" },
      { id: "t4-6", title: "ETFs e Índices", description: "Investindo no mercado todo", content: "ETFs seguem índices como IBOVESPA.", duration: "5 min", xpReward: 70, isCompleted: false, isLocked: true, isPro: true, icon: "TrendingUp", category: "Simplicidade" },
    ],
  },
  {
    id: "trail-5",
    title: "Cripto para Iniciantes",
    description: "Desvende o Bitcoin e a nova economia digital.",
    icon: "Zap",
    color: "from-orange-500 to-red-600",
    isPro: true,
    totalLessons: 4,
    completedLessons: 0,
    lessons: [
      { id: "t5-1", title: "O que é Bitcoin?", description: "Ouro Digital", content: "A primeira moeda descentralizada do mundo.", activityContent: "Entenda por que a escassez dá valor ao Bitcoin.", duration: "6 min", xpReward: 90, isCompleted: false, isLocked: true, isPro: true, icon: "Coins", category: "Cripto", tips: ["Bitcoin não tem dono.", "Not Your Keys, Not Your Coins."] },
      { id: "t5-2", title: "Ethereum e Smart Contracts", description: "O computador mundial", content: "Ethereum permite contratos autoexecutáveis.", duration: "7 min", xpReward: 100, isCompleted: false, isLocked: true, isPro: true, icon: "TrendingUp", category: "Tecnologia" },
      { id: "t5-3", title: "Wallets e Segurança", description: "Proteja suas chaves", content: "Guarde suas chaves privadas com segurança.", duration: "5 min", xpReward: 80, isCompleted: false, isLocked: true, isPro: true, icon: "Shield", category: "Segurança" },
      { id: "t5-4", title: "Altcoins e DeFi", description: "O futuro das finanças", content: "Finanças descentralizadas sem intermediários.", duration: "6 min", xpReward: 95, isCompleted: false, isLocked: true, isPro: true, icon: "Sparkles", category: "Inovação" },
    ],
  },
]
